routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::prefix(getenv('APP_ADMIN_URL'))
    ->namespace('Auth')
    ->group(static function () {
        Route::get('login', 'LoginController@showLoginForm')->name('login');
        Route::post('login', 'LoginController@login');
        Route::post('logout', 'LoginController@logout')->name('logout');
    });

Route::prefix(getenv('APP_ADMIN_URL'))
    ->namespace('Admin')
    ->as('admin.')
    ->middleware('auth')
    ->group(static function () {
        Route::get('/', 'AdminController')->name('index');
        Route::resource('device', 'AdminDeviceController')->except(['show']);
        Route::resource('device/{deviceId}/video', 'AdminVideoController')->except(['show']);
        Route::resource('device/{device}/photo', 'AdminPhotoController')->except(['edit', 'show', 'update']);
        Route::resource('review', 'AdminReviewController')->except(['create', 'show', 'store']);
    });

Route::get('/', 'IndexController@index')->name('index');
Route::get('sitemap', 'SitemapController');
Route::post('review', 'ReviewController@store')->name('review.store');

Route::prefix('{deviceType}')
    ->group(static function () {
        Route::get('', 'TypeController');
        Route::get('search', 'SearchController@filters')->name('device.search');
        Route::prefix('{brandSlug}')
            ->group(static function () {
                Route::get('', 'BrandController');
                Route::get('{deviceSlug}', 'DeviceController');
            });
    });

app/Http/Controllers/ReviewController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateReviewRequest;
use App\Models\Rating;
use App\Models\Review;
use App\Repositories\DeviceRepository;
use App\Repositories\QuestionRepository;

class ReviewController extends Controller
{
    private $deviceRepo;

    private $questionRepo;

    public function __construct(DeviceRepository $deviceRepo, QuestionRepository $questionRepo)
    {
        $this->deviceRepo = $deviceRepo;
        $this->questionRepo = $questionRepo;
    }

    //Создание отзыва.
    public function store(CreateReviewRequest $request)
    {
        $input = $request->all();
        $device = $this->deviceRepo->findOrFail($input['device_id']);
        $requiredQuestionIds = $this->questionRepo->getIdsByTypeId($device->type_id);
        foreach ($requiredQuestionIds as $questionId) {
            if (!isset($input['rating'][$questionId]) || !in_array($input['rating'][$questionId], [1, 2, 3, 4, 5])) {
                die('Оценка не валидна');
            }
        }

        $review = new Review([
            'device_id' => $input['device_id'],
            'name' => $input['name'],
            'is_published' => 0,
            'review' => $input['review'],
        ]);
        $review->save();
        foreach ($requiredQuestionIds as $questionId) {
            $review->ratings()->save(new Rating([
                'question_id' => $questionId,
                'value' => $input['rating'][$questionId],
            ]));
        }
        \Session::flash('review_sent', 'Спасибо, отзыв отправлен.');

        return redirect($_SERVER['HTTP_REFERER'] . '#review-add');
    }
}

resources/views/admin/review/edit.blade.php
@extends('admin/layouts/default')

@section('content')
    <h1>{{ $view['title'] }}</h1>

    @include('admin.include.errorsList')

    {!! Form::model($view['review'], [
        'action' => ['Admin\AdminReviewController@update', $view['review']->id],
        'method' => 'PATCH',
    ]) !!}

        <div class="form-group">
            {!! Form::label('name', 'Name:') !!}
            {!! Form::text('name', null, ['class' => 'form-control']) !!}
        </div>

        <div class="form-group">
            {!! Form::label('review', 'Review:') !!}
            {!! Form::textarea('review', null, ['class' => 'form-control']) !!}
        </div>

        <div class="form-group">
            {!! Form::label('is_published', 'Is published:') !!}
            {!! Form::select('is_published', [0, 1], null, ['class' => 'form-control']) !!}
        </div>

        <div class="form-group">
            {!! Form::submit('Сохранить', ['class' => 'btn btn-primary']) !!}
            @include('admin.include.deleteButton', ['dataId' => $view['review']->id])
        </div>

    {!! Form::close() !!}

    @include('admin.include.confirmDelete', ['formAction' => route('admin.review.index')])

@stop

resources/views/admin/review/index.blade.php
@extends('admin/layouts/default')

@section('content')

    <h1>{{ $view['title'] }}</h1>

    @if (count($reviewsList))
        <table class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">is published</th>
                    <th scope="col">name</th>
                    <th scope="col">review</th>
                    <th scope="col">created at</th>
                </tr>
            </thead>
            <tbody>
            @foreach ($reviewsList as $review)
                <tr>
                    <th scope="row">
                        <a href="{{ route('admin.review.edit', $review->id) }}">{{ $review->id }}</a>
                    </th>
                    <td>
                        <span
                                class="badge badge-{{ $review->is_published ? 'success' : 'warning' }} badge-pill"
                        >{{ $review->is_published }}</span>
                    </td>
                    <td>{{ $review->name }}</td>
                    <td>{{ $review->formattedReview }}</td>
                    <td>{{ $review->formattedCreatedAt }}</td>
                </tr>
            @endforeach
            </tbody>
        </table>
    @endif

@stop