routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::prefix(getenv('APP_ADMIN_URL'))
    ->namespace('Auth')
    ->group(static function () {
        Route::get('login', 'LoginController@showLoginForm')->name('login');
        Route::post('login', 'LoginController@login');
        Route::post('logout', 'LoginController@logout')->name('logout');
    });

Route::prefix(getenv('APP_ADMIN_URL'))
    ->namespace('Admin')
    ->as('admin.')
    ->middleware('auth')
    ->group(static function () {
        Route::get('/', 'AdminController')->name('index');
        Route::resource('device', 'AdminDeviceController')->except(['show']);
        Route::resource('device/{deviceId}/video', 'AdminVideoController')->except(['show']);
        Route::resource('device/{device}/photo', 'AdminPhotoController')->except(['edit', 'show', 'update']);
        Route::resource('review', 'AdminReviewController')->except(['create', 'show', 'store']);
    });

Route::get('/', 'IndexController@index')->name('index');
Route::get('sitemap', 'SitemapController');
Route::post('review', 'ReviewController@store')->name('review.store');

Route::prefix('{deviceType}')
    ->group(static function () {
        Route::get('', 'TypeController');
        Route::get('search', 'SearchController@filters')->name('device.search');
        Route::prefix('{brandSlug}')
            ->group(static function () {
                Route::get('', 'BrandController');
                Route::get('{deviceSlug}', 'DeviceController');
            });
    });

resources/views/admin/include/confirmDelete.blade.php
<div
        class="modal fade"
        id="defaultModal"
        tabindex="-1"
        role="dialog"
        aria-labelledby="defaultModalLabel"
        aria-hidden="true"
>
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="defaultModalLabel">Внимание!</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            {!! Form::open([
                'url' => $formAction,
                'id' => 'defaultModalForm',
                'method' => 'delete',
            ]) !!}

                <div class="modal-body" id="idModalBody"></div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Отмена</button>

                    {!! Form::submit('Удалить', ['class' => 'btn btn-danger']) !!}
                </div>

            {!! Form::close() !!}

        </div>
    </div>
</div>
<script>
    $('#defaultModal').on('show.bs.modal', function (event) {
        let button = $(event.relatedTarget);
        let recipient = button.data('id');
        let modal = $(this);
        modal.find('#defaultModalForm').attr(
            'action',
            '{{ $formAction }}/' + recipient
        );
        modal.find('#idModalBody').text('Удалить элемент # ' + recipient + '?');
        modal.find('#id').val(recipient);
    })
</script>

resources/views/admin/include/deleteButton.blade.php
<button
        class="btn btn-danger"
        data-target="#defaultModal"
        data-toggle="modal"
        data-id="{{ $dataId }}"
        title="Удалить"
        type="button"
>Удалить</button>

resources/views/admin/include/deleteXButton.blade.php
<button
        class="close"
        data-target="#defaultModal"
        data-toggle="modal"
        data-id="{{ $dataId }}"
        title="Удалить"
        type="button"
>&times;</button>

resources/views/admin/include/errorsList.blade.php
@if ($errors->any())
    <div class="alert alert-danger" role="alert">
        @foreach ($errors->all() as $error)
            {{ $error }}<br>
        @endforeach
    </div>
@endif

resources/views/admin/include/menu.blade.php
<br>
<ul class="list-group">
    <li class="list-group-item">
        <a href="{{ route('admin.device.index') }}">Девайсы</a>
        <span class="badge badge-info badge-pill">{{ $view['devicesCount'] }}</span>
    </li>
    <li class="list-group-item">
        <a href="{{ route('admin.review.index') }}">Отзывы</a>
        <span class="badge badge-info badge-pill">{{ $view['reviewsCount']['all'] }}</span>
        @if($view['reviewsCount']['isNotPublished'])
            <span class="badge badge-warning badge-pill">{{ $view['reviewsCount']['isNotPublished'] }}</span>
        @endif
    </li>
    <li class="list-group-item">
        <a
                class="text-warning"
                href="{{ route('logout') }}"
                onclick="event.preventDefault(); document.getElementById('logout-form').submit();"
        >Выйти</a>
        {!! Form::open(['route' => 'logout', 'id' => 'logout-form']) !!}
        {!! Form::close() !!}
    </li>
</ul>