routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::prefix(getenv('APP_ADMIN_URL'))
    ->namespace('Auth')
    ->group(static function () {
        Route::get('login', 'LoginController@showLoginForm')->name('login');
        Route::post('login', 'LoginController@login');
        Route::post('logout', 'LoginController@logout')->name('logout');
    });

Route::prefix(getenv('APP_ADMIN_URL'))
    ->namespace('Admin')
    ->as('admin.')
    ->middleware('auth')
    ->group(static function () {
        Route::get('/', 'AdminController')->name('index');
        Route::resource('device', 'AdminDeviceController')->except(['show']);
        Route::resource('device/{deviceId}/video', 'AdminVideoController')->except(['show']);
        Route::resource('device/{device}/photo', 'AdminPhotoController')->except(['edit', 'show', 'update']);
        Route::resource('review', 'AdminReviewController')->except(['create', 'show', 'store']);
    });

Route::get('/', 'IndexController@index')->name('index');
Route::get('sitemap', 'SitemapController');
Route::post('review', 'ReviewController@store')->name('review.store');

Route::prefix('{deviceType}')
    ->group(static function () {
        Route::get('', 'TypeController');
        Route::get('search', 'SearchController@filters')->name('device.search');
        Route::prefix('{brandSlug}')
            ->group(static function () {
                Route::get('', 'BrandController');
                Route::get('{deviceSlug}', 'DeviceController');
            });
    });

app/Models/Device.php
<?php

namespace App\Models;

use App\Models\Chars\Char;
use App\Models\Chars\DeviceChar;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;

/**
 * Class Device
 *
 * @package App\Models
 *
 * @property int $id
 * @property int $type_id
 * @property int $brand_id
 * @property bool $is_published
 * @property string $name
 * @property Carbon $last_modified
 * @property Carbon $release_date
 *
 * @property-read string $slug
 * @property-read string $formatted_release_date
 * @property-read string $path_to_photos
 *
 * @property-read Brand $brand
 * @property-read Type $type
 * @property-read Collection|Char[] $chars
 * @property-read Collection|DeviceChar[] $deviceChars
 * @property-read Collection|Review[] $reviews
 * @property-read Collection|Video[] $videos
 *
 * @method Builder|self published()
 * @method Builder|self whereBrandId(string $brandId)
 * @method Builder|self whereTypeId(string $typeId)
 */
class Device extends Model
{
    use HasSlug;

    /**
     * @inheritDoc
     */
    public $timestamps = false;

    /**
     * @inheritDoc
     */
    protected $guarded = [];

    /**
     * @inheritDoc
     */
    protected $dates = [
        'last_modified',
        'release_date',
    ];

    /**
     * @return string
     */
    public function getFormattedReleaseDateAttribute(): string
    {
        if (!$this->release_date) {
            return '';
        }

        $months = [
            1 => 'январь',
            2 => 'февраль',
            3 => 'март',
            4 => 'апрель',
            5 => 'май',
            6 => 'июнь',
            7 => 'июль',
            8 => 'август',
            9 => 'сентябрь',
            10 => 'октябрь',
            11 => 'ноябрь',
            12 => 'декабрь',
        ];
        $month = $months[$this->release_date->month];

        return $this->release_date->formatLocalized("$month %Y");
    }

    /**
     * @return string
     */
    public function getPathToPhotosAttribute(): string
    {
        return 'devices/' . $this->type->slug . '/' . $this->brand->slug . '/' . $this->slug;
    }

    /**
     * @return BelongsTo
     */
    public function brand(): BelongsTo
    {
        return $this->belongsTo(Brand::class);
    }

    /**
     * @return BelongsTo
     */
    public function type(): BelongsTo
    {
        return $this->belongsTo(Type::class);
    }

    /**
     * @return BelongsToMany
     */
    public function chars(): BelongsToMany
    {
        return $this
            ->belongsToMany(Char::class, DeviceChar::TABLE_NAME)
            ->withPivot(['value']);
    }

    /**
     * @return HasMany
     */
    public function deviceChars(): HasMany
    {
        return $this->hasMany(DeviceChar::class);
    }

    /**
     * @return HasMany|Review
     */
    public function reviews(): HasMany
    {
        return $this->hasMany(Review::class);
    }

    /**
     * @return HasMany
     */
    public function videos(): HasMany
    {
        return $this->hasMany(Video::class);
    }

    /**
     * @param Builder $query
     *
     * @return Builder
     */
    public function scopePublished(Builder $query): Builder
    {
        return $query->where('devices.is_published', '=', true);
    }
}

app/Http/Controllers/DeviceController.php
<?php

namespace App\Http\Controllers;

use App\Helper;
use App\Models\Brand;
use App\Models\Type;
use App\Repositories\BrandRepository;
use App\Repositories\DeviceRepository;
use App\Repositories\RatingRepository;
use App\Repositories\ReviewRepository;
use App\Repositories\TypeRepository;
use App\Repositories\VideoRepository;
use App\Services\CharGroupsToDeviceLoader;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Support\Facades\Storage;
use Illuminate\View\View;

class DeviceController extends Controller
{
    private $typeRepo;

    private $brandRepo;

    private $deviceRepo;

    private $videoRepo;

    private $reviewRepo;

    private $ratingRepo;

    private $helper;

    /**
     * @var CharGroupsToDeviceLoader
     */
    private $charGroupsToDeviceLoader;

    public function __construct(
        CharGroupsToDeviceLoader $charGroupsToDeviceLoader,
        TypeRepository $typeRepo,
        BrandRepository $brandRepo,
        DeviceRepository $deviceRepo,
        VideoRepository $videoRepo,
        ReviewRepository $reviewRepo,
        RatingRepository $ratingRepo,
        Helper $helper
    ) {
        $this->charGroupsToDeviceLoader = $charGroupsToDeviceLoader;
        $this->typeRepo = $typeRepo;
        $this->brandRepo = $brandRepo;
        $this->deviceRepo = $deviceRepo;
        $this->videoRepo = $videoRepo;
        $this->reviewRepo = $reviewRepo;
        $this->ratingRepo = $ratingRepo;
        $this->helper = $helper;
    }

    /**
     * @param Type $deviceType
     * @param string $brandSlug
     * @param string $deviceSlug
     *
     * @return View
     */
    public function __invoke(Type $deviceType, string $brandSlug, string $deviceSlug): View
    {
        $types = $this->typeRepo->getList();
        $brands = $this->brandRepo->getListByTypeId($deviceType->id);
        $currentBrand = $this->getCurrentBrandFromBrands($brands, $brandSlug);
        if (!$currentBrand) {
            abort(404);
        }
        $devices = $this->deviceRepo->getAllByTypeIdAndBrandId($deviceType->id, $currentBrand->id);
        $deviceId = $this->getCurrentDeviceIdFromDevices($devices, $deviceSlug);
        if (!$deviceId) {
            abort(404);
        }

        //Сайдбар меню.
        foreach ($devices as $device) {
            $device->isCurrent = ($device->id === $deviceId) ? true : false;
        }
        foreach ($brands as $brand) {
            $brand->devicesList = ($brand->id === $currentBrand->id) ? $devices : null;
        }
        foreach ($types as $type) {
            $type->brands = ($type->id === $deviceType->id) ? $brands : null;
        }

        $currentDevice = $this->deviceRepo->find($deviceId);
        $photoNames = Storage::disk('public')->allFiles($currentDevice->path_to_photos);
        $photos = [];
        foreach ($photoNames as $photoName) {
            $photos[] = Storage::disk('public')->url($photoName);
        }
        $this->charGroupsToDeviceLoader->load($currentDevice);
        $questions = $deviceType->questions;
        $reviews = $currentDevice->reviews()->published()->get();
        if (count($reviews)) {
            $reviewIds = [];
            foreach ($reviews as $review) {
                $reviewIds[] = $review->id;
            }
            $averageRating = $this->ratingRepo->getQuestionIdsAndAverageRatingAssoc($reviewIds);
            foreach ($questions as $question) {
                $question->averageRating = round((float) $averageRating[$question->id], 1);
                $question->cssWidth = (int) ($averageRating[$question->id] * 10 * 5);
            }
            //Общая оценка.
            $commonRating = 0.0;
            foreach ($questions as $question) {
                $commonRating += $question->averageRating;
            }
            $commonRating = round($commonRating / count($questions), 1);
        }

        $view = [
            'commonRating' => isset($commonRating) ? $commonRating : null,
            'brand' => $currentBrand,
            'breadCrumbs' => [
                0 => [
                    'name' => 'Главная',
                    'href' => '/',
                ],
                1 => [
                    'name' => $deviceType->name_plural,
                    'href' => '/' . $deviceType->slug,
                ],
                2 => [
                    'name' => $currentBrand->name,
                    'href' => '/' . $deviceType->slug . '/' . $currentBrand->slug,
                ],
                3 => [
                    'name' => $currentDevice->name,
                    'href' => '',
                ],
            ],
            'device' => $currentDevice,
            'questions' => $questions,
            'reviews' => $reviews,
            'reviewsCountWordForm' => $this->helper->getWordForm(count($reviews), ['отзыва', 'отзывов', 'отзывов']),
            'seo' => [
                'canonical' => '/' . $deviceType->slug . '/' . $currentBrand->slug . '/' . $currentDevice->slug,
                'description' => 'Мнения владельцев о ' . $deviceType->name_prepositional . ' ' .
                    $currentBrand->name . ' ' . $currentDevice->name . '. Реальные отзывы, оценки, ' .
                    'характеристики, фото, видео.',
                'keywords' => mb_strtolower($deviceType->name_singular) . ', ' . strtolower($currentBrand->name) .
                    ', ' . strtolower($currentDevice->name) . ', отзывы, оценка, мнения, написать отзыв, ' .
                    'технические характеристики, фото, видео, обзор',
                'title' => 'Отзывы о ' . $deviceType->name_prepositional . ' ' . $currentBrand->name . ' ' .
                    $currentDevice->name,
            ],
            'sidebarMenu' => $types,
            'type' => $deviceType,
            'videos' => $this->videoRepo->getListByDeviceId($currentDevice->id),
        ];

        return view('device.index', compact(['photos', 'view']));
    }

    /**
     * @param Collection|Brand[] $brands
     * @param string $slug
     *
     * @return Brand|null
     *
     * @TODO Вынести в трейт или что-то другое
     */
    private function getCurrentBrandFromBrands(Collection $brands, string $slug): ?Brand
    {
        foreach ($brands as $brand) {
            if ($slug === $brand->slug) {
                return $brand;
            }
        }

        return null;
    }

    //TODO php 7.2. Написать, что возвращает метод (?int).
    private function getCurrentDeviceIdFromDevices(Collection $devices, string $slug)
    {
        foreach ($devices as $device) {
            if ($slug === $device->slug) {
                return $device->id;
            }
        }

        return null;
    }
}

resources/views/admin/device/create.blade.php
@extends('admin/layouts/default')

@section('content')

    <h1>{{ $view['title'] }}</h1>

    @include('admin.include.errorsList')

    {!! Form::open(['route' => 'admin.device.store']) !!}

        @include('admin.device.form-fields', ['submitButtonText' => 'Создать'])

    {!! Form::close() !!}

@stop

resources/views/admin/device/edit.blade.php
<?php /** @var App\Models\Device $device */ ?>

@extends('admin/layouts/default')

@section('content')

    <h1>{{ $view['title'] }}</h1>

    @include('admin.include.errorsList')

    {!! Form::model($device, [
        'action' => ['Admin\AdminDeviceController@update', $device->id],
        'method' => 'PATCH',
    ]) !!}

        @include('admin.device.form-fields', ['submitButtonText' => 'Сохранить'])

    {!! Form::close() !!}

    <hr>

    <p>
        <a href="{{ route('admin.photo.index', $device->id) }}">Фото</a>
        <span
                class="badge badge-{{ $view['countPhoto'] ? 'info' : 'warning' }} badge-pill"
        >{{ $view['countPhoto'] }}</span>
    </p>

    <p>
        <a href="{{ route('admin.video.index', $device->id) }}">Видео</a>
        <span
                class="badge badge-{{ $view['countVideo'] ? 'info' : 'warning' }} badge-pill"
        >{{ $view['countVideo'] }}</span>
    </p>
@stop

resources/views/admin/device/form-fields.blade.php
<?php /** @var App\Models\Device $device */?>

<div class="form-group">
    {!! Form::label('type_id', 'Type:') !!}
    {!! Form::select('type_id', $view['typesAssoc'], null, ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('brand_id', 'Brand:') !!}
    {!! Form::select('brand_id', $view['brandsAssoc'], null, ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('name', 'Name:') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('release_date', 'Release date:') !!}
    {!! Form::date(
        'release_date',
        isset($device->release_date) ? $device->release_date->formatLocalized('%Y-%m-%d') : null,
        ['class' => 'form-control']
    ) !!}
</div>

<div class="form-check">
    {!! Form::checkbox('is_published', null, null, ['class' => 'form-check-input', 'id' => 'is_published']) !!}
    {!! Form::label('is_published', 'Is published:') !!}
</div>

{!! Form::submit($submitButtonText, ['class' => 'btn btn-primary']) !!}

resources/views/admin/device/index.blade.php
<?php /** @var App\Models\Device[] $devices */ ?>

@extends('admin/layouts/default')

@section('content')

    <h1>{{ $view['title'] }}</h1>
    <a class="btn btn-primary" href="{{ route('admin.device.create') }}" role="button">Создать</a><br><br>
    @if (count($devices))
        <table class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">type</th>
                    <th scope="col">brand</th>
                    <th scope="col">name</th>
                    <th scope="col">release date</th>
                    <th scope="col">last modified</th>
                    <th scope="col"  class="text-secondary">На сайте</th>
                    <th scope="col" class="text-right text-secondary">Удалить</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($devices as $device)
                    <tr>
                        <th scope="row">
                            <a href="{{ route('admin.device.edit', $device->id) }}">{{ $device->id }}</a>
                        </th>
                        <td>{{ $device->type->name_singular }}</td>
                        <td>{{ $device->brand->name }}</td>
                        <td>{{ $device->name }}</td>
                        <td>{{ $device->release_date }}</td>
                        <td>{{ $device->last_modified }}</td>
                        <td>
                            <a
                                href="/{{ $device->type->slug }}/{{ $device->brand->slug }}/{{ $device->slug }}"
                            >Ссылка</a>
                        </td>
                        <td>

                            @include('admin.include.deleteXButton', ['dataId' => $device['id']])

                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>

        @include('admin.include.confirmDelete', ['formAction' => route('admin.device.index')])

    @endif

@stop